<a href="https://colab.research.google.com/github/mohamedyosef101/101_learning_area/blob/area/PyTorch/00_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*This is part of PyTorch for deep learning course by Daniel Bourke.*

For more, check the [*source code*](https://github.com/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb).

# What is a **Tensor**?

**Tensors:** an n-dimensional arrary of numbers (where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector).

> *The word tensor comes form an old latin word which means to stretch.*

<div align="left">
  <img width="180" src="https://i.ibb.co/bdJ4Xyj/3-axis-numpy.png">
  <img width="188" src="https://i.ibb.co/pxZFrM8/3-axis-front.png">
  <img width="120" src="https://i.ibb.co/rxp1Gdm/3-axis-block.png">
</div>

**NOTE** the terms matrix and tensor are often used interchangably.

<div><br></div>

### Tensors have shapes. Some vocabulary:

* **Shape:** The length (number of elements) of each of the axes of a tensor.

* **Rank:** Number of tensor axes. A scalar has rank 0, a vector has rank 1, a matrix is rank 2.

* **Axis or Dimension:** A particular dimension of a tensor.

* **Size:** The total number of items in the tensor, the product of the shape vector's elements.

<div><br></div>

*more resources:*

- Dan Fleisch. (2011). [*What's a Tensor?*](https://youtu.be/f5liqUk0ZTw?si=eoUM7IJ8PbYyvK1I). YouTube.

- TensorFlow Core. [*Introduction to Tensors*](https://www.tensorflow.org/guide/tensor)

In [1]:
# set up
import torch
import numpy as np
import datetime as dt

print(f"Last run time: {dt.datetime.now()}")

Last run time: 2024-01-20 10:41:09.661066


### Scalar or rank-0 tensor
A scalar contains a single value, and no "axes".

In [2]:
scalar = torch.tensor(4)
print(f"scalar is a rank-{scalar.ndim} tensor")

scalar is a rank-0 tensor


![scalar](https://i.ibb.co/vQwMrQK/scalar.png)

### Vector or rank-1 tensor
Is like a list of values and has one axis.

In [3]:
vector = torch.tensor([2.0, 3.0, 4.0])
print(f"vector is a rank-{vector.ndim} tensor")

vector is a rank-1 tensor


![vector](https://i.ibb.co/9YWmdZw/vector.png)

### Matrix or rank-2 tensor
Has two axes

In [4]:
matrix = torch.tensor([[1, 2],
                      [3, 4],
                      [5, 6]])
print(f"matrix is a rank-{matrix.ndim} tensor")

matrix is a rank-2 tensor


![matrix](https://i.ibb.co/NLwfK1m/matrix.png)

### Rank-3 tensor
A tensor with three axes

In [5]:
numbers = torch.tensor([
    [[0, 1, 3, 3, 4],
     [5, 6, 7, 8, 9]],

    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],

    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]]
])

print(f"numbers is a rank-{numbers.ndim} tensor with shape {np.array(numbers.shape)}")

numbers is a rank-3 tensor with shape [3 2 5]


There are many ways to visualize this tensor:
<div align="left">
  <img width="180" src="https://i.ibb.co/bdJ4Xyj/3-axis-numpy.png">
  <img width="188" src="https://i.ibb.co/pxZFrM8/3-axis-front.png">
  <img width="120" src="https://i.ibb.co/rxp1Gdm/3-axis-block.png">
</div>

# *Random, Zeros, Ones, range, and like* **Tensors**

In [6]:
# create a random tensor of size (2, 3)
rand_MATRIX = torch.rand(size=(2,3))
rand_MATRIX

tensor([[0.4975, 0.2105, 0.8710],
        [0.6477, 0.0437, 0.5232]])

In [7]:
# create a tensor of all zeros
zeros_TENSOR = torch.zeros(size=(2, 1, 3))
zeros_TENSOR

tensor([[[0., 0., 0.]],

        [[0., 0., 0.]]])

In [8]:
# create a torch of all ones
ones_M = torch.ones(size=(2, 2))
ones_M

tensor([[1., 1.],
        [1., 1.]])

### Creating a **range of numbers** with tensors

Let's say I want to print a list of years from 1996 to 2030.

In [9]:
years = torch.arange(start=1996, step=1, end=2031)
years

tensor([1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007,
        2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019,
        2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030])

### **like** Tensors

In [10]:
years_prob = torch.ones_like(input=years)
years_prob

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Linear Algebra **Operations**

In [11]:
# matrix multiplication in tf
matrix_square = torch.matmul(matrix, torch.t(matrix)) # t for transpose
print(f"Original matrix: \n{np.array(matrix)}\nSquared one: \n{np.array(matrix_square)}")

Original matrix: 
[[1 2]
 [3 4]
 [5 6]]
Squared one: 
[[ 5 11 17]
 [11 25 39]
 [17 39 61]]


In [12]:
# the dot product
X = torch.tensor([[1, 2, 3], [1, 2, 3]])
Y = torch.tensor([[4, 5, 6], [1, 2, 3]])

torch.tensordot(X, Y, dims=2)

tensor(46)

---
# **Exercises**

## Create a random tensor with shape `(7, 7)`

In [13]:
import torch
tensor1 = torch.rand(size=[7, 7])
tensor1

tensor([[0.3671, 0.3910, 0.6521, 0.6592, 0.3934, 0.9245, 0.4407],
        [0.7708, 0.9036, 0.2309, 0.6017, 0.7896, 0.9025, 0.8673],
        [0.5812, 0.2049, 0.1889, 0.8241, 0.8502, 0.6220, 0.0142],
        [0.6697, 0.0967, 0.0684, 0.6757, 0.7449, 0.3434, 0.5914],
        [0.1138, 0.8930, 0.9740, 0.5993, 0.9152, 0.6749, 0.3106],
        [0.8822, 0.7312, 0.8643, 0.5308, 0.5684, 0.5843, 0.2629],
        [0.5336, 0.3425, 0.4077, 0.2231, 0.1753, 0.3221, 0.8060]])

In [14]:
tensor2 = torch.rand(size=[1, 7])

torch.matmul(tensor1, torch.t(tensor2))

tensor([[2.0651],
        [2.3628],
        [1.8202],
        [1.5957],
        [2.5074],
        [2.6458],
        [1.4132]])

In [15]:
torch.manual_seed(0)

tensor1 = torch.rand(size=[7, 7])
tensor2 = torch.rand(size=[1, 7])

torch.matmul(tensor1, torch.t(tensor2))

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [16]:
# check for access to GPU
torch.cuda.is_available()

True

In [18]:
torch.cuda.manual_seed(1234)

# create two random tensors on GPU
t1 = torch.rand(size=[2, 3], device='cuda')
t2 = torch.rand(size=[2, 3], device='cuda')
t1, t2

(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255],
         [0.1114, 0.6812, 0.3608]], device='cuda:0'))

In [31]:
t3 = torch.matmul(t1, torch.t(t2))
t3

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

In [28]:
# find the max and min value
print(f"max: {t3.max()}\nmin: {t3.min()}")

max: 0.7667766809463501
min: 0.27863210439682007


In [33]:
# find the max and min indexes
print(f"max index: {t3.argmax()}\nmin index: {t3.argmin()}")

max index: 1
min index: 0


In [35]:
torch.manual_seed(7)
a = torch.rand(size=[1, 1, 1, 10])
b = torch.rand(size=[10])
print(a, a.shape, b, b.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10]) tensor([0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204, 0.0731, 0.9699,
        0.1078]) torch.Size([10])
