<a href="https://colab.research.google.com/github/mohamedyosef101/learning_area/blob/area/TensorFlow/00_Intro_to_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is a Tensor?

**Tensors:** an n-dimensional arrary of numbers (where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector).

> *The word tensor comes form an old latin word which means to stretch.*

<div align="left">
  <img width="180" src="https://www.tensorflow.org/static/guide/images/tensor/3-axis_numpy.png">
  <img width="188" src="https://www.tensorflow.org/static/guide/images/tensor/3-axis_front.png">
  <img width="120" src="https://www.tensorflow.org/static/guide/images/tensor/3-axis_block.png">
</div>

**NOTE** the terms matrix and tensor are often used interchangably.

<div><br></div>

### Tensors have shapes. Some vocabulary:

* **Shape:** The length (number of elements) of each of the axes of a tensor.

* **Rank:** Number of tensor axes. A scalar has rank 0, a vector has rank 1, a matrix is rank 2.

* **Axis or Dimension:** A particular dimension of a tensor.

* **Size:** The total number of items in the tensor, the product of the shape vector's elements.

<div><br></div>

*more resources:*
- TensorFlow Core. [*Introduction to Tensors*](https://www.tensorflow.org/guide/tensor)

- Dan Fleisch. 2011. [*What's a Tensor?*](https://youtu.be/f5liqUk0ZTw?si=eoUM7IJ8PbYyvK1I). YouTube.

In [ ]:
# set up
import tensorflow as tf
import datetime as dt

print(f"Last run time: {dt.datetime.now()}")

Last run time: 2023-12-27 18:48:32.240930


### Scalar or rank-0 tensor
A scalar contains a single value, and no "axes".

In [ ]:
scalar = tf.constant(4)
print(scalar)

# You can also you variable instead of constant
# the difference is same as in math.

tf.Tensor(4, shape=(), dtype=int32)


![scalar](https://www.tensorflow.org/static/guide/images/tensor/scalar.png)

### Vector or rank-1 tensor
Is like a list of values and has one axis.

In [ ]:
vector = tf.constant([2.0, 3.0, 4.0])
print(vector)

tf.Tensor([2 3 4], shape=(3,), dtype=int32)


![vector](https://www.tensorflow.org/static/guide/images/tensor/vector.png)

### Matrix or rank-2 tensor
Has two axes

In [ ]:
matrix = tf.constant([[1, 2],
                      [3, 4],
                      [5, 6]])
print(matrix)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


![matrix](https://www.tensorflow.org/static/guide/images/tensor/matrix.png)

### Rank-3 tensor
A tensor with three axes

In [ ]:
rank_3_tensor = tf.constant([
    [[0, 1, 3, 3, 4],
     [5, 6, 7, 8, 9]],

    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],

    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]]
])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  3  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


There are many ways to visualize this tensor:
<div align="left">
  <img width="180" src="https://www.tensorflow.org/static/guide/images/tensor/3-axis_numpy.png">
  <img width="188" src="https://www.tensorflow.org/static/guide/images/tensor/3-axis_front.png">
  <img width="120" src="https://www.tensorflow.org/static/guide/images/tensor/3-axis_block.png">
</div>

# Linear Algebra **Operations**

In [ ]:
# matrix multiplication in tf
matrix_square = tf.matmul(matrix, tf.transpose(matrix))
print(f"Original matrix: \n{matrix}\nSquared one: \n{matrix_square}")

Original matrix: 
[[1 2]
 [3 4]
 [5 6]]
Squared one: 
[[ 5 11 17]
 [11 25 39]
 [17 39 61]]


In [ ]:
# the dot product
X = tf.constant([[1, 2], [1, 2], [1, 2]])
Y = tf.constant([[4, 5, 6], [1, 2, 3]])
tf.tensordot(X, Y, axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 6,  9, 12],
       [ 6,  9, 12],
       [ 6,  9, 12]], dtype=int32)>