<a href="https://colab.research.google.com/github/mohamedyosef101/101_learning_area/blob/area/d2l/Preliminaries/2_1-data-manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Manipulation
**Source**: [Dive into Deep Learning](https://d2l.ai)

In [1]:
import torch

In [4]:
x = torch.arange(12, dtype=torch.int32)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=torch.int32)


In [5]:
# the total number of elements
x.numel()

12

In [9]:
print("shape:", x.shape)
print("better shape:", x.detach().numpy().shape)

shape: torch.Size([12])
better shape: (12,)


In [11]:
X = x.reshape(2, 6)
print(X)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]], dtype=torch.int32)


In [13]:
# high rank tensor
torch.zeros((2, 1, 3), dtype=torch.int32)

tensor([[[0, 0, 0]],

        [[0, 0, 0]]], dtype=torch.int32)

In [15]:
torch.ones((3, 1, 2), dtype=torch.int)

tensor([[[1, 1]],

        [[1, 1]],

        [[1, 1]]], dtype=torch.int32)

In [20]:
# random tensor from normal distribution
R = torch.randn((2, 3, 1), dtype=torch.float32)
print(R)

tensor([[[-0.8074],
         [-0.9482],
         [-1.1078]],

        [[ 0.2802],
         [ 1.3105],
         [ 0.7219]]])


In [23]:
R[-1], R[0:2]

(tensor([[0.2802],
         [1.3105],
         [0.7219]]),
 tensor([[[-0.8074],
          [-0.9482],
          [-1.1078]],
 
         [[ 0.2802],
          [ 1.3105],
          [ 0.7219]]]))