<a href="https://colab.research.google.com/github/mohamedyosef101/101_learning_area/blob/area/d2l/Preliminaries/2_1-data-manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Manipulation
**Source**: [Dive into Deep Learning](https://d2l.ai)

In [17]:
import torch

In [2]:
x = torch.arange(12, dtype=torch.int32)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=torch.int32)


In [3]:
# the total number of elements
x.numel()

12

In [4]:
print("shape:", x.shape)
print("better shape:", x.detach().numpy().shape)

shape: torch.Size([12])
better shape: (12,)


In [5]:
X = x.reshape(2, 6)
print(X)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]], dtype=torch.int32)


In [6]:
# high rank tensor
torch.zeros((2, 1, 3), dtype=torch.int32)

tensor([[[0, 0, 0]],

        [[0, 0, 0]]], dtype=torch.int32)

In [7]:
torch.ones((3, 1, 2), dtype=torch.int)

tensor([[[1, 1]],

        [[1, 1]],

        [[1, 1]]], dtype=torch.int32)

In [8]:
# random tensor from normal distribution
R = torch.randn((2, 3, 1), dtype=torch.float32)
print(R)

tensor([[[ 1.9287],
         [-0.4666],
         [-2.2394]],

        [[-0.4869],
         [-1.2403],
         [ 0.5022]]])


# Indexing and Slicing

In [9]:
R[-1], R[0:2]

(tensor([[-0.4869],
         [-1.2403],
         [ 0.5022]]),
 tensor([[[ 1.9287],
          [-0.4666],
          [-2.2394]],
 
         [[-0.4869],
          [-1.2403],
          [ 0.5022]]]))

In [10]:
R[-1][-1] = 0
print(R)

tensor([[[ 1.9287],
         [-0.4666],
         [-2.2394]],

        [[-0.4869],
         [-1.2403],
         [ 0.0000]]])


In [14]:
X[:1, :] = 1
print(X)

tensor([[ 1,  1,  1,  1,  1,  1],
        [ 6,  7,  8,  9, 10, 11]], dtype=torch.int32)


In [15]:
X[-1:, :] = 2
print(X)

tensor([[1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2]], dtype=torch.int32)


# Operations

In mathematical notation, we denote such *unary* scalar operators (taking one input) by the signature $f: \mathbb R \to \mathbb R$. This is means that the function maps from any real number onto some other real number. Most standard operators, including unary ones like $e^x$, can be applied elementwise.

In [16]:
torch.exp(x)

tensor([2.7183, 2.7183, 2.7183, 2.7183, 2.7183, 2.7183, 7.3891, 7.3891, 7.3891,
        7.3891, 7.3891, 7.3891])

Likewise, we denote binary scalar operators, which map pairs of real numbers to a (single) real number via the signature $f: \mathbb R, \mathbb R \to \mathbb R$. Given any two vectors $u$ and $v$ of the same shape, and a binary operator $f$, we can produce a vector $c = F(u, v)$ by setting $c_i \gets f(u_i, v_i)$ for all $i$, where $c_i$, $u_i$, and the $i^th$ elements of the vectors $c, u$, and $v$.

In [23]:
u = torch.arange(4, dtype=torch.int32)
v = torch.ones(4, dtype=torch.int32)
c = u * v
print(f"u = {u.numpy()}\nv = {v.numpy()}\nc = {c.numpy()}")

u = [0 1 2 3]
v = [1 1 1 1]
c = [0 1 2 3]


| Standard arithmetic operators |
| ---------------------------- |
| addition  ( **+** ) |
| subtraction ( **-** ) |
| multiplication ( * ) |
| division ( **/** ) |
| exponentiation ( ** ) |

The example belwo shows what happens when we concatenate two matrices along rows (axis 0) and along columns (axis 1).

In [29]:
M1 = torch.arange(12).reshape((3,4))
M2 = torch.zeros((3, 4))
print(M1, "\n\n", M2, "\n ===================== \n")

cat_rows = torch.cat((M1, M2), dim=0)
cat_cols = torch.cat((M1, M2), dim=1)
print(f"Concate along rows \n{cat_rows.numpy()}" +
      f"\nConcate along columns \n{cat_cols.numpy()}")

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]) 

 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) 

Concate along rows 
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
Concate along columns 
[[ 0.  1.  2.  3.  0.  0.  0.  0.]
 [ 4.  5.  6.  7.  0.  0.  0.  0.]
 [ 8.  9. 10. 11.  0.  0.  0.  0.]]


In [31]:
# logical statement
print(M1 == M2)

tensor([[ True, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [32]:
M1.sum()

tensor(66)

## Broadcasting
Used when shapes differ to do elementwise binary operations by:
1. expand one or both arrays by copying elements along axes with length 1 so that after this transforamtion, the two tensors have the same shape;
2. perfrom an elementwise operation on the resulting arrays.

In [33]:
a = torch.arange(4).reshape((4,1))
b = torch.ones((1, 3))
print(f"Before broadcasting: \n{a} \n\n{b}\n" +
      "\n=====================================\n\n" +
      f"After broadcasting: \n{a + b}")

# it duplicates tensor a, b to be 4x3

Before broadcasting: 
tensor([[0],
        [1],
        [2],
        [3]]) 

tensor([[1., 1., 1.]])


After broadcasting: 
tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.]])


## Saving Memory

In [38]:
before = id(X)
X = 1 + X
print(f"Before: {before}\nAfter: {id(X)}")

Before: 138147779964384
After: 138147778394160


## Summary
The tensor class is the main interface for storing and manipulating data in deep learning libraries. Tensors provide a variety of functionalities including construction routines; indexing and slicing; basic mathematics operations; broadcasting; memory-efficient assignment; and conversion to and from other Python objects.