<a href="https://colab.research.google.com/github/mohamedyosef101/101_learning_area/blob/area/d2l/Preliminaries/2_3-linear-algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra

**Sources**:
- Aston Zhang et al. 2023. https://d2l.ai
- Grant Standerson. 2016. [Essence of linear algebra](https://youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab&si=wDPSsMVaR7Yvl3QJ)

In [2]:
import torch

## Reduction

In [6]:
A = torch.arange(12).reshape(3,4)
A, A.sum()

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor(66))

In [8]:
A.sum(dim=0) # reduces row dimension

tensor([12, 15, 18, 21])

In [5]:
A.sum(dim=1) # reduces column dimension

tensor([ 6, 22, 38])

In [10]:
A.sum(dim=1, keepdim=True)

tensor([[ 6],
        [22],
        [38]])

In [11]:
A.cumsum(dim=1)

tensor([[ 0,  1,  3,  6],
        [ 4,  9, 15, 22],
        [ 8, 17, 27, 38]])

## Products & Multiplications

In [18]:
x, y = torch.tensor([1, 3, 2]), torch.tensor([2, 3, 4])
torch.dot(x, y), torch.sum(x*y), x@y

(tensor(19), tensor(19), tensor(19))

In [23]:
# matrix-vector multiplication
A = torch.arange(6).reshape(2,3)
torch.mv(A, x), A@x

(tensor([ 7, 25]), tensor([ 7, 25]))

In [24]:
# matrix-matrix multiplication
torch.mm(A, A.T), A@A.T

(tensor([[ 5, 14],
         [14, 50]]),
 tensor([[ 5, 14],
         [14, 50]]))